#!/bin/csh -f
#          _/             _/_/
#        _/_/           _/_/_/
#      _/_/_/_/         _/_/_/
#      _/_/_/_/_/       _/_/_/              ____________________________________________ 
#      _/_/_/_/_/       _/_/_/             /                                           / 
#      _/_/_/_/_/       _/_/_/            /                               N25Q128A13B / 
#      _/_/_/_/_/       _/_/_/           /                                           /  
#      _/_/_/_/_/_/     _/_/_/          /                                   128Mbit / 
#      _/_/_/_/_/_/     _/_/_/         /                              SERIAL FLASH / 
#      _/_/_/ _/_/_/    _/_/_/        /                                           / 
#      _/_/_/  _/_/_/   _/_/_/       /                  Verilog Behavioral Model / 
#      _/_/_/   _/_/_/  _/_/_/      /                               Version 1.7 / 
#      _/_/_/    _/_/_/ _/_/_/     /                                           /
#      _/_/_/     _/_/_/_/_/_/    /           Copyright (c) 2011 Numonyx B.V. / 
#      _/_/_/      _/_/_/_/_/    /___________________________________________/ 
#      _/_/_/       _/_/_/_/      
#      _/_/          _/_/_/  
# 
#     
#             NUMONYX              


set RUNDIR  = ./
set LIBDIR  = ./include
set CODEDIR = ./code
set STIMDIR = ./stim
set TOPDIR  = ./top
set SIMDIR  = ./sim
set HDLPATH = ./hdl.var
set CDSPATH = ./cds.lib


if (-e work) then
\rm -r work
endif
mkdir work


#CODE
ncvlog  -cdslib $CDSPATH -hdlvar $HDLPATH -MESSAGES -NOCOPYRIGHT -LINEDEBUG   $CODEDIR/N25Q128A13B.v
if ( $status != 0 ) exit 3


#STIM
ncvlog  -cdslib $CDSPATH -hdlvar $HDLPATH -MESSAGES -NOCOPYRIGHT -LINEDEBUG  $STIMDIR/read.v
if ( $status != 0 ) exit 4


#TOP
ncvlog  -cdslib $CDSPATH -hdlvar $HDLPATH -MESSAGES -NOCOPYRIGHT -LINEDEBUG  $TOPDIR/Testbench.v
if ( $status != 0 ) exit 5
ncvlog  -cdslib $CDSPATH -hdlvar $HDLPATH -MESSAGES -NOCOPYRIGHT -LINEDEBUG  $TOPDIR/StimTasks.v
if ( $status != 0 ) exit 5
ncvlog  -cdslib $CDSPATH -hdlvar $HDLPATH -MESSAGES -NOCOPYRIGHT -LINEDEBUG  $TOPDIR/ClockGenerator.v
if ( $status != 0 ) exit 5


cd $SIMDIR


# Elaborate
ncelab -cdslib ../$CDSPATH -hdlvar ../$HDLPATH -mess -NOWARN CUDEFB work.Testbench -access +r
if ( $status != 0 ) exit 6


# Simulate
ncsim -cdslib ../$CDSPATH -hdlvar ../$HDLPATH work.Testbench -gui  $1 &
if ( $status != 0 ) exit 7


