# See LICENSE for license details.

`include "./qspi_controller/qspi_define.v"
`include "./qspi_controller/qspi_ahb_if.v"
`include "./qspi_controller/qspi_axi4_if.v"
`include "./qspi_controller/qspi_cmd_gen.v"
`include "./qspi_controller/qspi_fsm.v"
`include "./qspi_controller/qspi_inst_decode.v"
`include "./qspi_controller/qspi_top.v"
`include "./qspi_controller/qspi_tran_rec.v"
`include "./qspi_controller/qspi_cchan_inst_gen.v"
`include "./qspi_controller/qspi_clk_divider.v"
`include "./qspi_controller/qspi_ctrl_level.v"
`include "./qspi_controller/qspi_data_lock.v"
`include "./qspi_controller/qspi_inst_arbiter.v"
`include "./qspi_controller/qspi_inst_buffer.v"
`include "./qspi_controller/qspi_interface_level.v"
`include "./qspi_controller/qspi_mode_ctrl.v"
`include "./qspi_controller/qspi_tran_level.v"
`include "./qspi_controller/MEM/fifo/qspi_addr_fifo.v"
`include "./qspi_controller/MEM/fifo/qspi_data_fifo_32.v"
`include "./qspi_controller/MEM/fifo/qspi_info_fifo.v"
